//------------------------------------------------------------------------------
// FileName = Configuration.cs
// Generated at 04/18/2014 00:49:06
//
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//    NOTE: Please use the Add a Reference to System.Configuration assembly if 
//          you get compile errors with ConfigurationManager
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Configuration;
 
namespace Insight.Website
{
    public static class AppSettings 
	{
		private static string GetSettingOrDefault(string setting, string defaultValue)
		{
			if (string.IsNullOrEmpty(setting))
			{
				return defaultValue;
			}
			else 
			{
				return setting;
			}
		}

		private static TimeSpan GetTimeSpanSettingOrDefault(string setting, TimeSpan defaultValue)
		{
			TimeSpan ts;
			if (!TimeSpan.TryParse(setting, out ts))
			{
				return defaultValue;
			}
			else 
			{
				return ts;
			}
		}

		public static readonly string webpages_Version = GetSettingOrDefault(ConfigurationManager.AppSettings["webpages:Version"], "3.0.0.0");
		public static readonly string webpages_Enabled = GetSettingOrDefault(ConfigurationManager.AppSettings["webpages:Enabled"], "false");
		public static readonly string ClientValidationEnabled = GetSettingOrDefault(ConfigurationManager.AppSettings["ClientValidationEnabled"], "true");
		public static readonly string UnobtrusiveJavaScriptEnabled = GetSettingOrDefault(ConfigurationManager.AppSettings["UnobtrusiveJavaScriptEnabled"], "true");
	}

    public static class ConnectionStrings 
	{
		public static readonly ConnectionStringSettings LocalSqlServer = ConfigurationManager.ConnectionStrings["LocalSqlServer"];
		public static readonly ConnectionStringSettings DefaultConnection = ConfigurationManager.ConnectionStrings["DefaultConnection"];
	}
}
